import { VerticalBox, HorizontalBox, Button, LineEdit } from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "Cloubit";
    min-width: 1050px;
    min-height: 590px;
    callback play-audio(string);
    callback pause-audio();
    callback resume-audio();
    callback seek-audio(string);

    ContextMenuArea {
        Menu {
            MenuItem {
                title: "Test form 1";
            }

            MenuItem {
                title: "Test form 2";
            }
        }

        VerticalBox {
            ContextMenuArea {
                height: 250px;
                Menu {
                    MenuItem {
                        title: "Copy(TEST FORM)";
                    }
                }

                Image {
                    rotation-angle: 0deg;
                    source: @image-url("../resources/logo.svg");
                    vertical-alignment: ImageVerticalAlignment.center;
                    height: 250px;
                }
            }

            Text {
                text: "Hello, Cloubit!";
                vertical-alignment: TextVerticalAlignment.top;
                wrap: TextWrap.word-wrap;
                font-size: 30px;
                height: 48px;
                horizontal-alignment: TextHorizontalAlignment.center;
            }

            HorizontalBox {
                padding: 20px;
                spacing: 10px;
                input-field := LineEdit {
                    placeholder-text: "Enter audio URL...";
                    font-size: 14px;
                    preferred-width: 400px;
                }

                play-button := Button {
                    text: "Play Audio";
                    preferred-width: 100px;
                    clicked => {
                        root.play-audio(input-field.text);
                    }
                }
            }

            HorizontalBox {
                padding: 20px;
                spacing: 10px;

                pause-button := Button {
                    text: "Pause Audio";
                    preferred-width: 100px;
                    clicked => {
                        root.pause-audio();
                    }
                }

                resume-button := Button {
                    text: "Resume Audio";
                    preferred-width: 100px;
                    clicked => {
                        root.resume-audio();
                    }
                }

                seek-pos := LineEdit {
                    placeholder-text: "Enter seek time...";
                    font-size: 14px;
                    preferred-width: 400px;
                }

                seek-button := Button {
                    text: "Seek Audio";
                    preferred-width: 100px;
                    clicked => {
                        root.seek-audio(seek-pos.text);
                    }
                }
            }
        }
    }
}
