name: Build
on:
    push:
        branches:
            - master
            - refactor
    pull_request:
        branches:
            - master

jobs:
    release:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-22.04, windows-latest]
        runs-on: ${{ matrix.platform }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Install dependencies(Ubuntu)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    libgtk-3-dev \
                    libwebkit2gtk-4.1-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev \
                    build-essential \
                    perl \
                    nasm

            - name: Install dependencies(windows)
              if: matrix.platform == 'windows-latest'
              run: |
                  choco install -y strawberryperl
                  choco install -y nasm
                  $perlPath = "C:\Strawberry\perl\bin"
                  $nasmPath = "C:\Program Files\NASM"
                  Add-Content $env:GITHUB_PATH "$perlPath"
                  Add-Content $env:GITHUB_PATH "$nasmPath"

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Cache Rust builds
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: './src-tauri -> target'

            - name: Build Tauri app
              run: pnpm tauri build
              env:
                  OPENSSL_DIR: ${{ matrix.platform == 'windows-latest' && 'C:\\Program Files\\OpenSSL-Win64' || '' }}
                  OPENSSL_LIB_DIR: ${{ matrix.platform == 'windows-latest' && 'C:\\Program Files\\OpenSSL-Win64\\lib' || '' }}
                  OPENSSL_INCLUDE_DIR: ${{ matrix.platform == 'windows-latest' && 'C:\\Program Files\\OpenSSL-Win64\\include' || '' }}

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: release-${{ matrix.platform }}-${{ github.sha }}
                  path: |
                      src-tauri/target/release/bundle/deb/*.deb
                      src-tauri/target/release/bundle/appimage/*.AppImage
                      src-tauri/target/release/bundle/rpm/*.rpm

                      src-tauri/target/release/*.exe
                      src-tauri/target/release/bundle/msi/*.msi

                      src-tauri/target/release/bundle/dmg/*.dmg
                      src-tauri/target/release/bundle/macos/*.app
                  retention-days: 7
