name: Build
on:
    push:
        branches:
            - master
            - refactor
    pull_request:
        branches:
            - master

jobs:
    release:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-22.04, windows-latest]
        runs-on: ${{ matrix.platform }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies(Ubuntu)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    build-essential \
                    perl \
                    nasm \
                    libasound2-dev \
                    pkg-config

            - name: Install dependencies(windows)
              if: matrix.platform == 'windows-latest'
              run: |
                  choco install -y strawberryperl
                  choco install -y nasm
                  $perlPath = "C:\Strawberry\perl\bin"
                  $nasmPath = "C:\Program Files\NASM"
                  Add-Content $env:GITHUB_PATH "$perlPath"
                  Add-Content $env:GITHUB_PATH "$nasmPath"

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Cache Rust builds
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: './ -> target'

            - name: Build Slint app
              run: cargo build --release
              env:
                  OPENSSL_DIR: ${{ matrix.platform == 'windows-latest' && 'C:\\Program Files\\OpenSSL-Win64' || '' }}
                  OPENSSL_LIB_DIR: ${{ matrix.platform == 'windows-latest' && 'C:\\Program Files\\OpenSSL-Win64\\lib' || '' }}
                  OPENSSL_INCLUDE_DIR: ${{ matrix.platform == 'windows-latest' && 'C:\\Program Files\\OpenSSL-Win64\\include' || '' }}

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: release-${{ matrix.platform }}-${{ github.sha }}
                  path: |
                      target/release/cloubit.exe
                      target/release/cloubit
                      !target/release/cloubit.d
                  retention-days: 7
